-- seed_skills.sql  (30 skills)
-- Load order: 2 of 7
INSERT INTO Skill (name) VALUES
    ('Python'),
    ('Java'),
    ('C++'),
    ('SQL'),
    ('JavaScript'),
    ('TypeScript'),
    ('React'),
    ('Node.js'),
    ('Flask'),
    ('Spring Boot'),
    ('Docker'),
    ('Kubernetes'),
    ('AWS'),
    ('Azure'),
    ('Cybersecurity'),
    ('Network Security'),
    ('Penetration Testing'),
    ('Machine Learning'),
    ('Data Analysis'),
    ('Data Engineering'),
    ('Linux'),
    ('Git'),
    ('REST APIs'),
    ('GraphQL'),
    ('PostgreSQL'),
    ('MongoDB'),
    ('Redis'),
    ('Agile / Scrum'),
    ('Technical Writing'),
    ('Cloud Architecture');
